/**
 * THIS FILE IS AUTOGENERATED, DO NOT MODIFY. EDIT THE FILES IN templates/
 * AND RUN ./gradlew :codegen INSTEAD!
 */

package ${namespace}.matrix

import koma.*
import koma.matrix.*
import koma.extensions.*
import koma.internal.notImplemented
import koma.internal.getRng
import koma.internal.syncNotNative

class Default${dtype}MatrixFactory: MatrixFactory<Matrix<${dtype}>> {
    override fun zeros(rows: Int, cols: Int) 
            = Default${dtype}Matrix(rows, cols)

    override fun create(data: IntRange): Matrix<${dtype}> {
        val input = data.map { it.to${dtype}() }
        val out = Default${dtype}Matrix(1, input.size)
        input.forEachIndexed { idx, ele -> out[idx] = ele }
        return out
    }    
    override fun create(data: DoubleArray): Matrix<${dtype}> {
        val out = Default${dtype}Matrix(1, data.size)
        data.forEachIndexed { idx, ele -> out[idx] = ele.to${dtype}() }
        return out
    }

    override fun create(data: Array<DoubleArray>): Matrix<${dtype}> {
        val out = Default${dtype}Matrix(data.size, data[0].size)
        data.forEachIndexed { rowIdx, row ->
            row.forEachIndexed { colIdx, ele -> 
                out[rowIdx, colIdx] = ele.to${dtype}()
            }
        }
        return out
    }

    override fun ones(rows: Int, cols: Int): Matrix<${dtype}>
            = zeros(rows, cols).fill {_,_-> 1.to${dtype}()}

    override fun eye(size: Int): Matrix<${dtype}> 
            = eye(size, size)
    override fun eye(rows: Int, cols: Int): Matrix<${dtype}>
            = zeros(rows, cols)
            .fill {row,col->if (row==col) 1.to${dtype}() else 0.to${dtype}() }


    override fun rand(rows: Int, cols: Int): Matrix<${dtype}> {
        val array = zeros(rows, cols)
        val rng = getRng()
        syncNotNative(rng) {
            array.fill { _, _ -> rng.nextDoubleUnsafe().to${ dtype }() }
        }
        return array;
    }


    override fun randn(rows: Int, cols: Int): Matrix<${dtype}> {
        val array = zeros(rows, cols)
        val rng = getRng()
        syncNotNative(rng) {
            array.fill { _, _ -> rng.nextGaussianUnsafe().to${ dtype }() }
        }
        return array;
    }


    override fun arange(start: Double, stop: Double, increment: Double): Matrix<${dtype}> {
        error(notImplemented)
    }

    override fun arange(start: Double, stop: Double): Matrix<${dtype}> {
        error(notImplemented)
    }

    override fun arange(start: Int, stop: Int, increment: Int): Matrix<${dtype}> {
        error(notImplemented)
    }

    override fun arange(start: Int, stop: Int): Matrix<${dtype}> {
        error(notImplemented)
    }
}
