/**
 * THIS FILE IS AUTOGENERATED, DO NOT MODIFY. EDIT THE FILES IN templates/
 * AND RUN ./gradlew :codegen INSTEAD!
 */

package ${namespace}.ndarray

import koma.extensions.fill
import koma.ndarray.*

class Default${dtype}NDArrayFactory: NumericalNDArrayFactory<${dtype}> {
    override fun create(vararg lengths: Int,
                        filler: (IntArray) -> ${dtype}): NDArray<${dtype}> {
        return Default${dtype}NDArray(*lengths).also {
            it.fill{filler(it)}
        }
    }

    override fun zeros(vararg lengths: Int): NDArray<${dtype}> {
        return Default${dtype}NDArray(*lengths).fill {
            0.to${dtype}()
        }
    }

    override fun ones(vararg lengths: Int): NDArray<${dtype}> {
        return Default${dtype}NDArray(*lengths).fill {
            1.to${dtype}()
        }
    }

    override fun rand(vararg lengths: Int): NDArray<${dtype}> {
        return Default${dtype}NDArray(*lengths).fill {
            0.to${dtype}()
        }
    }

    override fun randn(vararg lengths: Int): NDArray<${dtype}> {
        return Default${dtype}NDArray(*lengths).fill {
            koma.internal.getRng().nextDouble().to${dtype}()
        }
    }

}
