@file:koma.internal.JvmName("NDArray")
@file:koma.internal.JvmMultifileClass

/**
 * THIS FILE IS AUTOGENERATED, DO NOT MODIFY. EDIT THE FILES IN templates/
 * AND RUN ./gradlew :codegen INSTEAD!
 */

package koma.extensions

import koma.internal.default.utils.reduceArrayAxis
import koma.internal.default.utils.argMinFloat
import koma.internal.default.utils.argMaxFloat
import koma.internal.default.utils.wrapIndex
import koma.ndarray.NDArray
import koma.ndarray.NumericalNDArrayFactory
import koma.pow
import koma.matrix.Matrix
import koma.util.IndexIterator

@koma.internal.JvmName("toMatrixFloat")
fun NDArray<Float>.toMatrix(): Matrix<Float> {
    if (this is Matrix)
        return this
    val dims = this.shape()
    return when (dims.size) {
        1 -> { Matrix.floatFactory.zeros(dims[0], 1).fill { row, _ -> this[row] } }
        2 -> { Matrix.floatFactory.zeros(dims[0], dims[1]).fill { row, col -> this[row, col] } }
        else -> error("Cannot convert NDArray with ${dims.size} dimensions to matrix (must be 1 or 2)")
    }
}

@koma.internal.JvmName("fillFloat")
inline fun  NDArray<Float>.fill(f: (idx: IntArray) -> Float) = apply {
    for ((nd, linear) in this.iterateIndices())
        this.setFloat(linear, f(nd))
}

@koma.internal.JvmName("fillFloatBoth")
inline fun  NDArray<Float>.fillBoth(f: (nd: IntArray, linear: Int) -> Float) = apply {
    for ((nd, linear) in this.iterateIndices())
        this.setFloat(linear, f(nd, linear))
}

@koma.internal.JvmName("fillFloatLinear")
inline fun  NDArray<Float>.fillLinear(f: (idx: Int) -> Float) = apply {
    for (idx in 0 until size)
        this.setFloat(idx, f(idx))
}

@koma.internal.JvmName("createFloat")
inline fun  NumericalNDArrayFactory<Float>.create(vararg lengths: Int, filler: (idx: IntArray) -> Float)
    = NDArray.floatFactory.zeros(*lengths).fill(filler)

/**
 * Returns a new NDArray with the given shape, populated with the data in this array.
 *
 * @param dims Desired dimensions of the output array.
 *
 * @returns A copy of the elements in this array, shaped to the given number of rows and columns,
 *          such that `this.toList() == this.reshape(*dims).toList()`
 *
 * @throws IllegalArgumentException when the product of all of the given `dims` does not equal [size]
 */
@koma.internal.JvmName("reshapeFloat")
fun  NDArray<Float>.reshape(vararg dims: Int): NDArray<Float> {
    if (dims.reduce { a, b -> a * b } != size)
        throw IllegalArgumentException("$size items cannot be reshaped to ${dims.toList()}")
    var idx = 0
    return NDArray.floatFactory.zeros(*dims).fill { _ -> getFloat(idx++) }
}


/**
 * Takes each element in a NDArray, passes them through f, and puts the output of f into an
 * output NDArray.
 *
 * @param f A function that takes in an element and returns an element
 *
 * @return the new NDArray after each element is mapped through f
 */
@koma.internal.JvmName("mapFloat")
inline fun <reified R> NDArray<Float>.map(crossinline f: (Float) -> R)
    = NDArray.createLinear(*shape().toIntArray(), filler={ f(this.getFloat(it)) } )

/**
 * Takes each element in a NDArray, passes them through f, and puts the output of f into an
 * output NDArray. Index given to f is a linear index, depending on the underlying storage
 * major dimension.
 *
 * @param f A function that takes in an element and returns an element. Function also takes
 *      in the linear index of the element's location.
 *
 * @return the new NDArray after each element is mapped through f
 */
@koma.internal.JvmName("mapIndexedFloat")
inline fun  NDArray<Float>.mapIndexed(f: (idx: Int, ele: Float) -> Float)
    = NDArray.floatFactory.zeros(*shape().toIntArray()).fillLinear { f(it, this.getFloat(it)) }


/**
 * Takes each element in a NDArray and passes them through f.
 *
 * @param f A function that takes in an element
 *
 */
@koma.internal.JvmName("forEachFloat")
inline fun  NDArray<Float>.forEach(f: (ele: Float) -> Unit) {
    // TODO: Change this back to iteration once there are non-boxing iterators
    for (idx in 0 until size)
        f(getFloat(idx))
}
/**
 * Takes each element in a NDArray and passes them through f. Index given to f is a linear
 * index, depending on the underlying storage major dimension.
 *
 * @param f A function that takes in an element. Function also takes
 *      in the linear index of the element's location.
 *
 */
@koma.internal.JvmName("forEachIndexedFloat")
inline fun  NDArray<Float>.forEachIndexed(f: (idx: Int, ele: Float) -> Unit) {
    // TODO: Change this back to iteration once there are non-boxing iterators
    for (idx in 0 until size)
        f(idx, getFloat(idx))
}

/**
 * Takes each element in a NDArray, passes them through f, and puts the output of f into an
 * output NDArray. Index given to f is the full ND index of the element.
 *
 * @param f A function that takes in an element and returns an element. Function also takes
 *      in the ND index of the element's location.
 *
 * @return the new NDArray after each element is mapped through f
 */
@koma.internal.JvmName("mapIndexedNFloat")
inline fun  NDArray<Float>.mapIndexedN(f: (idx: IntArray, ele: Float) -> Float): NDArray<Float>
    = NDArray.floatFactory.zeros(*shape().toIntArray()).fillBoth { nd, linear -> f(nd, getFloat(linear)) }


/**
 * Takes each element in a NDArray and passes them through f. Index given to f is the full
 * ND index of the element.
 *
 * @param f A function that takes in an element. Function also takes
 *      in the ND index of the element's location.
 *
 */
@koma.internal.JvmName("forEachIndexedNFloat")
inline fun  NDArray<Float>.forEachIndexedN(f: (idx: IntArray, ele: Float) -> Unit) {
    for ((nd, linear) in iterateIndices())
        f(nd, getFloat(linear))
}

/**
 * Converts this NDArray into a one-dimensional FloatArray in row-major order.
 */
fun  NDArray<Float>.toFloatArray() = FloatArray(size) { getFloat(it) }

fun <T> NDArray<T>.getSliceFloat(vararg indices: Any): NDArray<Float> {
    if (indices.size != shape().size)
        throw IllegalArgumentException("Specified ${indices.size} indices for an array with ${shape().size} dimensions")
    val indexArrays = mutableListOf<IntArray>()
    val outputShape = mutableListOf<Int>()
    val outputDims = mutableListOf<Int>()
    val inputIndex = kotlin.IntArray(indices.size)

    // Convert the inputs to arrays of integer indices.

    for (i in 0 until indices.size) {
        val index = indices[i]
        val size = shape()[i]
        if (index is Int) {
            inputIndex[i] = index
            indexArrays.add(kotlin.intArrayOf(wrapIndex(index, size)))
        }
        else if (index is Iterable<*>) {
            outputDims.add(i)
            indexArrays.add(index.map { wrapIndex(it as Int, size) }.toIntArray())
            outputShape.add(indexArrays.last().size)
        }
        else
            throw IllegalArgumentException("All indices must be Int or Iterable<Int>")
    }
    if (outputShape.size == 0)
        throw IllegalArgumentException("A slice must have at least one dimension")

    // Create the output array.

    val lengths = outputShape.toIntArray()
    val filler = { index: IntArray ->
        for (i in 0 until outputDims.size)
            inputIndex[outputDims[i]] = indexArrays[outputDims[i]][index[i]]
        getFloat(*inputIndex)
    }
    return NDArray.floatFactory.zeros(*lengths).fill(filler)
}

fun <T> NDArray<T>.setSliceFloat(vararg indices: Any, value: Float) {
    if (indices.size != shape().size)
        throw IllegalArgumentException("Specified ${indices.size} indices for an array with ${shape().size} dimensions")
    val indexArrays = mutableListOf<IntArray>()

    // Convert the inputs to arrays of integer indices.

    for (i in 0 until indices.size) {
        val index = indices[i]
        val size = shape()[i]
        if (index is Int)
            indexArrays.add(kotlin.intArrayOf(wrapIndex(index, size)))
        else if (index is Iterable<*>)
            indexArrays.add(index.map { wrapIndex(it as Int, size) }.toIntArray())
        else
            throw IllegalArgumentException("All indices must be Int or Iterable<Int>")
    }

    // Set the elements.

    val lengths = IntArray(indices.size, { indexArrays[it].size })
    val element = IntArray(lengths.size)
    for ((nd, linear) in IndexIterator(lengths)) {
        for (i in 0 until element.size)
            element[i] = indexArrays[i][nd[i]]
        setFloat(*element, v=value)
    }
}

fun <T> NDArray<T>.setSliceFloat(vararg indices: Any, value: NDArray<Float>) {
    if (indices.size != shape().size)
        throw IllegalArgumentException("Specified ${indices.size} indices for an array with ${shape().size} dimensions")
    val indexArrays = mutableListOf<IntArray>()

    // Convert the inputs to arrays of integer indices.

    for (i in 0 until indices.size) {
        val index = indices[i]
        val size = shape()[i]
        if (index is Int)
            indexArrays.add(kotlin.intArrayOf(wrapIndex(index, size)))
        else if (index is Iterable<*>)
            indexArrays.add(index.map { wrapIndex(it as Int, size) }.toIntArray())
        else
            throw IllegalArgumentException("All indices must be Int or Iterable<Int>")
    }

    // Make sure the shapes match, after eliminating dimensions of size 1.

    val lengths = IntArray(indices.size, { indexArrays[it].size })
    val outputDims = lengths.filter { it != 1 }
    val inputDims = value.shape().filter { it != 1}
    if (!(outputDims.toIntArray() contentEquals inputDims.toIntArray()))
        throw IllegalArgumentException("Cannot assign a value of shape ${inputDims.toList()} to a slice of shape ${outputDims.toList()}")

    // Set the elements.

    val element = IntArray(lengths.size)
    for ((nd, linear) in IndexIterator(lengths)) {
        for (i in 0 until element.size)
            element[i] = indexArrays[i][nd[i]]
        setFloat(*element, v=value.getFloat(linear))
    }
}

@koma.internal.JvmName("setFloat")
operator fun  NDArray<Float>.set(vararg indices: Int, value: NDArray<Float>) {
    val lastIndex = indices.mapIndexed { i, range -> range + value.shape()[i] }
    val outOfBounds = lastIndex.withIndex().any { it.value > shape()[it.index] }
    if (outOfBounds)
        throw IllegalArgumentException("NDArray with shape ${shape()} cannot be " +
                "set at ${indices.toList()} by a ${value.shape()} array " +
                "(out of bounds)")

    val offset = indices.map { it }.toIntArray()
    value.forEachIndexedN { idx, ele ->
        val newIdx = offset.zip(idx).map { it.first + it.second }.toIntArray()
        this.setGeneric(indices=*newIdx, v=ele)
    }
}

/**
 * Find the linear index of the minimum element in this array.
 */
@koma.internal.JvmName("argMinFloat")
fun  NDArray<Float>.argMin(): Int = argMinInternal()

/**
 * Find the linear index of the minimum element along one axis of this array,  returning the result in a new array.
 * If the array contains non-comparable values, this throws an exception.
 * 
 * @param axis      the axis to compute the minimum over
 * @param keepdims  if true, the output array has the same number of dimensions as the original one,
 *                  with [axis] having size 1.  If false, the output array has one fewer dimensions
 *                  than the original one.
 */
@koma.internal.JvmName("argMinAxisFloat")
fun  NDArray<Float>.argMin(axis: Int, keepdims: Boolean): NDArray<Int> =
    reduceArrayAxis(this, { length: Int, get: (Int) -> Float -> argMinFloat(length, get) }, axis, keepdims)

/**
 * Find the value of the minimum element in this array.
 */
@koma.internal.JvmName("minFloat")
fun  NDArray<Float>.min(): Float = minInternal()

/**
 * Find the minimum element along one axis of this array, returning the result in a new array.
 * If the array contains non-comparable values, this throws an exception.
 *
 * @param axis      the axis to compute the minimum over
 * @param keepdims  if true, the output array has the same number of dimensions as the original one,
 *                  with [axis] having size 1.  If false, the output array has one fewer dimensions
 *                  than the original one.
 */
@koma.internal.JvmName("minAxisFloat")
inline fun  NDArray<Float>.min(axis: Int, keepdims: Boolean): NDArray<Float> =
    reduceArrayAxis(this, { length: Int, get: (Int) -> Float -> get(argMinFloat(length, get)) }, axis, keepdims)

/**
 * Find the linear index of the maximum element in this array.
 */
@koma.internal.JvmName("argMaxFloat")
fun  NDArray<Float>.argMax(): Int = argMaxInternal()

/**
 * Find the linear index of the maximum element along one axis of this array, returning the result in a new array.
 * If the array contains non-comparable values, this throws an exception.
 * 
 * @param axis      the axis to compute the maximum over
 * @param keepdims  if true, the output array has the same number of dimensions as the original one,
 *                  with [axis] having size 1.  If false, the output array has one fewer dimensions
 *                  than the original one.
 */
@koma.internal.JvmName("argMaxAxisFloat")
fun  NDArray<Float>.argMax(axis: Int, keepdims: Boolean): NDArray<Int> =
    reduceArrayAxis(this, { length: Int, get: (Int) -> Float -> argMaxFloat(length, get) }, axis, keepdims)

/**
 * Find the value of the maximum element in this array.
 */
@koma.internal.JvmName("maxFloat")
fun  NDArray<Float>.max(): Float = maxInternal()

/**
 * Find the maximum element along one axis of this array, returning the result in a new array.
 * If the array contains non-comparable values, this throws an exception.
 *
 * @param axis      the axis to compute the maximum over
 * @param keepdims  if true, the output array has the same number of dimensions as the original one,
 *                  with [axis] having size 1.  If false, the output array has one fewer dimensions
 *                  than the original one.
 */
@koma.internal.JvmName("maxAxisFloat")
inline fun  NDArray<Float>.max(axis: Int, keepdims: Boolean): NDArray<Float> =
    reduceArrayAxis(this, { length: Int, get: (Int) -> Float -> get(argMaxFloat(length, get)) }, axis, keepdims)

operator fun  NDArray<Float>.get(vararg indices: Int) = getFloat(*indices)
operator fun  NDArray<Float>.set(vararg indices: Int, value: Float) = setFloat(indices=*indices, v=value)


@koma.internal.JvmName("divFloat")
operator fun NDArray<Float>.div(other: Float) = map { (it/other).toFloat() }
@koma.internal.JvmName("timesArrFloat")
operator fun NDArray<Float>.times(other: NDArray<Float>) = mapIndexedN { idx, ele -> (ele*other.get(*idx)).toFloat() }
@koma.internal.JvmName("timesFloat")
operator fun NDArray<Float>.times(other: Float) = map { (it * other).toFloat() }
@koma.internal.JvmName("unaryMinusFloat")
operator fun NDArray<Float>.unaryMinus() = map { (-it).toFloat() }
@koma.internal.JvmName("minusFloat")
operator fun NDArray<Float>.minus(other: Float) = map { (it - other).toFloat() }
@koma.internal.JvmName("minusArrFloat")
operator fun NDArray<Float>.minus(other: NDArray<Float>) = mapIndexedN { idx, ele -> (ele - other.get(*idx)).toFloat() }
@koma.internal.JvmName("plusFloat")
operator fun NDArray<Float>.plus(other: Float) = map { (it + other).toFloat() }
@koma.internal.JvmName("plusArrFloat")
operator fun NDArray<Float>.plus(other: NDArray<Float>) = mapIndexedN { idx, ele -> (ele + other.get(*idx)).toFloat() }
@koma.internal.JvmName("powFloat")
infix fun NDArray<Float>.pow(exponent: Int) = map { pow(it.toDouble(), exponent).toFloat() }

