@file:koma.internal.JvmName("NDArray")
@file:koma.internal.JvmMultifileClass

/**
 * THIS FILE IS AUTOGENERATED, DO NOT MODIFY. EDIT THE FILES IN templates/
 * AND RUN ./gradlew :codegen INSTEAD!
 */

package koma.extensions

import koma.internal.default.generated.ndarray.DefaultGenericNDArray
import koma.internal.default.utils.checkIndices
import koma.internal.default.utils.linearToNIdx
import koma.matrix.doubleFactory
import koma.ndarray.NDArray
import koma.pow
import koma.matrix.Matrix

fun NDArray<Float>.toMatrix(): Matrix<Float> {
    if (this is Matrix)
        return this
    val dims = this.shape()
    return when (dims.size) {
        1 -> { Matrix.floatFactory.zeros(dims[0], 1).fill { row, _ -> this[row] } }
        2 -> { Matrix.floatFactory.zeros(dims[0], dims[1]).fill { row, col -> this[row, col] } }
        else -> error("Cannot convert NDArray with ${dims.size} dimensions to matrix (must be 1 or 2)")
    }
}

inline fun  NDArray<Float>.fill(f: (idx: IntArray) -> Float): NDArray<Float> {
    this.forEachIndexedN { idx, ele ->
        this.set(indices=*idx, value = f(idx))
    }
    return this
}


/**
 * Takes each element in a NDArray, passes them through f, and puts the output of f into an
 * output NDArray.
 *
 * @param f A function that takes in an element and returns an element
 *
 * @return the new NDArray after each element is mapped through f
 */
inline fun  NDArray<Float>.map(f: (Float) -> Float): NDArray<Float> {
    // TODO: Something better than copy here
    val out = this.copy()
    for ((idx, ele) in this.toIterable().withIndex())
        out.setLinear(idx, f(ele))
    return out
}
/**
 * Takes each element in a NDArray, passes them through f, and puts the output of f into an
 * output NDArray. Index given to f is a linear index, depending on the underlying storage
 * major dimension.
 *
 * @param f A function that takes in an element and returns an element. Function also takes
 *      in the linear index of the element's location.
 *
 * @return the new NDArray after each element is mapped through f
 */
inline fun  NDArray<Float>.mapIndexed(f: (idx: Int, ele: Float) -> Float): NDArray<Float> {
    // TODO: Something better than copy here
    val out = this.copy()
    for ((idx, ele) in this.toIterable().withIndex())
        out.setLinear(idx, f(idx, ele))
    return out
}
/**
 * Takes each element in a NDArray and passes them through f.
 *
 * @param f A function that takes in an element
 *
 */
inline fun  NDArray<Float>.forEach(f: (ele: Float) -> Unit) {
    for (ele in this.toIterable())
        f(ele)
}
/**
 * Takes each element in a NDArray and passes them through f. Index given to f is a linear
 * index, depending on the underlying storage major dimension.
 *
 * @param f A function that takes in an element. Function also takes
 *      in the linear index of the element's location.
 *
 */
inline fun  NDArray<Float>.forEachIndexed(f: (idx: Int, ele: Float) -> Unit) {
    for ((idx, ele) in this.toIterable().withIndex())
        f(idx, ele)
}

// TODO: for both of these, batch compute [linearToNIdx] instead of computing for every ele

/**
 * Takes each element in a NDArray, passes them through f, and puts the output of f into an
 * output NDArray. Index given to f is the full ND index of the element.
 *
 * @param f A function that takes in an element and returns an element. Function also takes
 *      in the ND index of the element's location.
 *
 * @return the new NDArray after each element is mapped through f
 */
inline fun  NDArray<Float>.mapIndexedN(f: (idx: IntArray, ele: Float) -> Float): NDArray<Float>
        = this.mapIndexed { idx, ele -> f(linearToNIdx(idx), ele) }

/**
 * Takes each element in a NDArray and passes them through f. Index given to f is the full
 * ND index of the element.
 *
 * @param f A function that takes in an element. Function also takes
 *      in the ND index of the element's location.
 *
 */
inline fun  NDArray<Float>.forEachIndexedN(f: (idx: IntArray, ele: Float) -> Unit)
        = this.forEachIndexed { idx, ele -> f(linearToNIdx(idx), ele) }


operator fun  NDArray<Float>.get(vararg indices: IntRange): NDArray<Float> {
    checkIndices(indices.map { it.last }.toIntArray())
    return DefaultGenericNDArray<Float>(shape = *indices
            .map { it.last - it.first + 1 }
            .toIntArray()) { newIdxs ->
        val offsets = indices.map { it.first }
        val oldIdxs = newIdxs.zip(offsets).map { it.first + it.second }
        this.getGeneric(*oldIdxs.toIntArray())
    }
}

operator fun  NDArray<Float>.set(vararg indices: Int, value: NDArray<Float>) {
    val shape = shape()
    val lastIndex = indices.mapIndexed { i, range -> range + value.shape()[i] }
    val outOfBounds = lastIndex.withIndex().any { it.value > shape()[it.index] }
    if (outOfBounds)
        throw IllegalArgumentException("NDArray with shape ${shape()} cannot be " +
                "set at ${indices.toList()} by a ${value.shape()} array " +
                "(out of bounds)")

    val offset = indices.map { it }.toIntArray()
    value.forEachIndexedN { idx, ele ->
        val newIdx = offset.zip(idx).map { it.first + it.second }.toIntArray()
        this.setGeneric(indices=*newIdx, value=ele)
    }
}


operator fun  NDArray<Float>.get(vararg indices: Int) = getFloat(*indices)
operator fun  NDArray<Float>.set(vararg indices: Int, value: Float) = setFloat(indices=*indices, value=value)


operator fun NDArray<Float>.div(other: Float) = map { (it/other).toFloat() }
operator fun NDArray<Float>.times(other: NDArray<Float>) = mapIndexedN { idx, ele -> (ele*other.get(*idx)).toFloat() }
operator fun NDArray<Float>.times(other: Float) = map { (it * other).toFloat() }
operator fun NDArray<Float>.unaryMinus() = map { (-it).toFloat() }
operator fun NDArray<Float>.minus(other: Float) = map { (it - other).toFloat() }
operator fun NDArray<Float>.minus(other: NDArray<Float>) = mapIndexedN { idx, ele -> (ele - other.get(*idx)).toFloat() }
operator fun NDArray<Float>.plus(other: Float) = map { (it + other).toFloat() }
operator fun NDArray<Float>.plus(other: NDArray<Float>) = mapIndexedN { idx, ele -> (ele + other.get(*idx)).toFloat() }
infix fun NDArray<Float>.pow(exponent: Int) = map { pow(it.toDouble(), exponent).toFloat() }

